// Product Database
window.PRODUCTS = [
  {
    id: 1,
    name: "Xbox One S 1TB",
    slug: "xbox-one-s-1tb",
    category: "consoles",
    price: 299.99,
    description:
      "Experience richer, more luminous colors in games and video with High Dynamic Range. Stream 4K video on Netflix, Amazon, and more. Play over 100 console exclusives. Connect and play with friends and family on Xbox Live, the most advanced multiplayer network.",
    image: "Xbox One S 1TB.jpg",
    stock: 15,
    rating: 4.5,
    reviewCount: 234,
    specs: {
      storage: "1TB HDD",
      resolution: "4K",
      features: ["HDR", "4K Streaming", "Xbox Live"],
    },
    vendor: "TechGaming Store",
    featured: true,
  },
  {
    id: 2,
    name: "Xbox 360 E 250GB",
    slug: "xbox-360-e-250gb",
    category: "consoles",
    price: 149.99,
    description:
      "Xbox 360 E console with 250GB hard drive. Play thousands of Xbox 360 games, stream movies and TV shows. Connect with friends on Xbox Live.",
    image: "Xbox 360 E 250GB.jpg",
    stock: 8,
    rating: 4.2,
    reviewCount: 156,
    specs: {
      storage: "250GB HDD",
      resolution: "1080p",
      features: ["Xbox Live", "DVD Playback"],
    },
    vendor: "RetroGaming Hub",
    featured: false,
  },
  {
    id: 3,
    name: "Sony PlayStation 3 Super Slim 500GB",
    slug: "ps3-super-slim-500gb",
    category: "consoles",
    price: 199.99,
    description:
      "PlayStation 3 Super Slim with 500GB storage. Play PS3 games, Blu-ray movies, and access PlayStation Network for multiplayer gaming and entertainment.",
    image: "Sony PlayStation 3 Super Slim 500GB.jpg",
    stock: 12,
    rating: 4.4,
    reviewCount: 189,
    specs: {
      storage: "500GB HDD",
      resolution: "1080p",
      features: ["Blu-ray", "PlayStation Network", "Streaming"],
    },
    vendor: "Console Central",
    featured: true,
  },
  {
    id: 4,
    name: "Sony PlayStation 4 Slim 1TB",
    slug: "ps4-slim-1tb",
    category: "consoles",
    price: 399.99,
    description:
      "PlayStation 4 Slim with 1TB storage. Experience incredible games and endless entertainment. Play exclusive PlayStation titles and connect with friends.",
    image: "Sony PlayStation 4 Slim 1TB.jpg",
    stock: 20,
    rating: 4.7,
    reviewCount: 512,
    specs: {
      storage: "1TB HDD",
      resolution: "1080p",
      features: ["HDR", "PlayStation Network", "Share Play"],
    },
    vendor: "Gaming Pro Shop",
    featured: true,
  },
  {
    id: 5,
    name: "Sony PlayStation 5 Console",
    slug: "ps5-console",
    category: "consoles",
    price: 499.99,
    description:
      "PlayStation 5 with ultra-high speed SSD, 4K-TV gaming, and up to 120fps. Experience lightning-fast loading, deeper immersion with haptic feedback, and a new generation of incredible PlayStation games.",
    image: "Sony PlayStation 5 Console.jpg",
    stock: 5,
    rating: 4.9,
    reviewCount: 876,
    specs: {
      storage: "825GB SSD",
      resolution: "4K/8K",
      features: ["Ray Tracing", "120fps", "3D Audio", "DualSense Controller"],
    },
    vendor: "Next-Gen Gaming",
    featured: true,
  },
  {
    id: 6,
    name: "Nintendo Switch OLED Model",
    slug: "nintendo-switch-oled",
    category: "consoles",
    price: 349.99,
    description:
      "Nintendo Switch OLED Model features a vibrant 7-inch OLED screen, enhanced audio, and 64GB of internal storage. Play at home or on the go with this versatile console.",
    image: "Nintendo Switch – OLED Model.jpg",
    stock: 18,
    rating: 4.8,
    reviewCount: 654,
    specs: {
      storage: "64GB",
      screen: "7-inch OLED",
      features: ["Portable/Docked", "Enhanced Audio", "Kickstand"],
    },
    vendor: "Nintendo Specialists",
    featured: true,
  },
  {
    id: 7,
    name: "Xbox Series X",
    slug: "xbox-series-x",
    category: "consoles",
    price: 499.99,
    description:
      "Xbox Series X delivers next-gen performance with 12 teraflops of processing power, DirectX ray tracing, and a custom SSD. Experience gaming in 4K at 120fps.",
    image: "Xbox Series X.jpg",
    stock: 10,
    rating: 4.8,
    reviewCount: 723,
    specs: {
      storage: "1TB SSD",
      resolution: "4K/8K",
      features: ["Ray Tracing", "120fps", "Quick Resume", "Smart Delivery"],
    },
    vendor: "Xbox Elite Store",
    featured: true,
  },
  {
    id: 8,
    name: "AMD Ryzen 9 7950X",
    slug: "amd-ryzen-9-7950x",
    category: "processors",
    price: 699.99,
    description:
      "AMD Ryzen 9 7950X 16-Core, 32-Thread processor with 5.7 GHz Max Boost. Incredible performance for gaming, content creation, and multitasking.",
    image: "AMD Ryzen 9 7950X.jpg",
    stock: 25,
    rating: 4.9,
    reviewCount: 412,
    specs: {
      cores: "16 Cores / 32 Threads",
      speed: "4.5 GHz Base / 5.7 GHz Boost",
      socket: "AM5",
      tdp: "170W",
    },
    vendor: "PC Components Pro",
    featured: true,
  },
  {
    id: 9,
    name: "Intel Core i9-14900K",
    slug: "intel-core-i9-14900k",
    category: "processors",
    price: 589.99,
    description:
      "Intel Core i9-14900K 24-Core processor with up to 6.0 GHz. Ultimate performance for gaming and content creation with Intel's latest architecture.",
    image: "Intel Core i9-14900K.jpg",
    stock: 30,
    rating: 4.8,
    reviewCount: 389,
    specs: {
      cores: "24 Cores (8P+16E)",
      speed: "3.2 GHz Base / 6.0 GHz Boost",
      socket: "LGA 1700",
      tdp: "125W Base / 253W Turbo",
    },
    vendor: "Intel Authorized",
    featured: false,
  },
  {
    id: 10,
    name: "Samsung Odyssey G9",
    slug: "samsung-odyssey-g9",
    category: "monitors",
    price: 1299.99,
    description:
      "Samsung Odyssey G9 49-inch curved gaming monitor with QLED, 240Hz, 1ms response time, and NVIDIA G-SYNC. Immersive ultra-wide gaming experience.",
    image: "Samsung Odyssey G9.jpg",
    stock: 7,
    rating: 4.7,
    reviewCount: 267,
    specs: {
      size: "49 inches",
      resolution: "5120x1440",
      refreshRate: "240Hz",
      panel: "VA QLED",
      features: ["G-SYNC", "FreeSync", "HDR1000"],
    },
    vendor: "Monitor Masters",
    featured: true,
  },
  {
    id: 11,
    name: "ASUS ROG Swift PG27AQDP",
    slug: "asus-rog-swift-pg27aqdp",
    category: "monitors",
    price: 899.99,
    description:
      "ASUS ROG Swift 27-inch OLED gaming monitor with 480Hz refresh rate, 0.03ms response time, and G-SYNC Ultimate. Professional esports gaming display.",
    image: "ASUS ROG Swift PG27AQDP.jpg",
    stock: 12,
    rating: 4.9,
    reviewCount: 198,
    specs: {
      size: "27 inches",
      resolution: "2560x1440",
      refreshRate: "480Hz",
      panel: "OLED",
      features: ["G-SYNC Ultimate", "HDR", "DisplayHDR True Black 400"],
    },
    vendor: "ASUS Gaming Direct",
    featured: true,
  },
  {
    id: 12,
    name: "Keychron Q1 Pro QMK",
    slug: "keychron-q1-pro-qmk",
    category: "peripherals",
    price: 189.99,
    description:
      "Keychron Q1 Pro wireless mechanical keyboard with QMK/VIA support. Premium aluminum build, hot-swappable switches, and RGB backlighting.",
    image: "Keychron Q1 Pro QMK.jpg",
    stock: 22,
    rating: 4.8,
    reviewCount: 345,
    specs: {
      layout: "75% (84 keys)",
      switches: "Hot-swappable",
      connectivity: "Wireless/Wired",
      features: ["QMK/VIA", "RGB", "Aluminum Frame"],
    },
    vendor: "Mechanical Keys Shop",
    featured: false,
  },
  {
    id: 13,
    name: "Corsair K70 RGB TKL",
    slug: "corsair-k70-rgb-tkl",
    category: "peripherals",
    price: 159.99,
    description:
      "Corsair K70 RGB TKL mechanical gaming keyboard. Tournament-ready tenkeyless design with Cherry MX switches and per-key RGB backlighting.",
    image: "Corsair K70 RGB TKL.jpg",
    stock: 28,
    rating: 4.6,
    reviewCount: 421,
    specs: {
      layout: "TKL (87 keys)",
      switches: "Cherry MX",
      connectivity: "Wired USB-C",
      features: ["Per-key RGB", "Tournament Mode", "Aluminum Frame"],
    },
    vendor: "Corsair Official",
    featured: false,
  },
  {
    id: 14,
    name: "Razer DeathAdder V3 Pro",
    slug: "razer-deathadder-v3-pro",
    category: "peripherals",
    price: 149.99,
    description:
      "Razer DeathAdder V3 Pro wireless gaming mouse. 30K DPI sensor, 90-hour battery life, and lightweight ergonomic design for competitive gaming.",
    image: "Razer DeathAdder V3 Pro.jpg",
    stock: 35,
    rating: 4.7,
    reviewCount: 567,
    specs: {
      sensor: "Focus Pro 30K",
      dpi: "30,000",
      connectivity: "Wireless 2.4GHz / Bluetooth",
      weight: "63g",
      features: ["HyperSpeed Wireless", "90hr Battery", "Gen-3 Optical Switches"],
    },
    vendor: "Razer Gaming Store",
    featured: true,
  },
  {
    id: 15,
    name: "Logitech G Pro X Superlight",
    slug: "logitech-g-pro-x-superlight",
    category: "peripherals",
    price: 159.99,
    description:
      "Logitech G Pro X Superlight wireless gaming mouse. Ultra-lightweight at 63g with HERO 25K sensor. Trusted by esports professionals worldwide.",
    image: "Logitech G Pro X Superlight.jpg",
    stock: 40,
    rating: 4.8,
    reviewCount: 689,
    specs: {
      sensor: "HERO 25K",
      dpi: "25,600",
      connectivity: "Wireless LIGHTSPEED",
      weight: "63g",
      features: ["LIGHTSPEED", "70hr Battery", "Zero Additive PTFE Feet"],
    },
    vendor: "Logitech G Official",
    featured: true,
  },
  {
    id: 16,
    name: "AMD Radeon RX 7900 XTX 24GB",
    slug: "amd-radeon-rx-7900-xtx",
    category: "graphics",
    price: 999.99,
    description:
      "AMD Radeon RX 7900 XTX graphics card with 24GB GDDR6 memory. Powered by AMD RDNA 3 architecture for exceptional 4K gaming performance.",
    image: "AMD Radeon RX 7900 XTX 24GB.jpg",
    stock: 14,
    rating: 4.6,
    reviewCount: 298,
    specs: {
      memory: "24GB GDDR6",
      coreClock: "2300 MHz Boost",
      interface: "PCIe 4.0",
      features: ["Ray Tracing", "FSR 3", "AV1 Encode"],
    },
    vendor: "GPU Headquarters",
    featured: true,
  },
  {
    id: 17,
    name: "NVIDIA GeForce RTX 4090 24GB",
    slug: "nvidia-geforce-rtx-4090",
    category: "graphics",
    price: 1599.99,
    description:
      "NVIDIA GeForce RTX 4090 flagship graphics card with 24GB GDDR6X. Unmatched performance powered by Ada Lovelace architecture for 4K and 8K gaming.",
    image: "NVIDIA GeForce RTX 4090 24GB.jpg",
    stock: 6,
    rating: 5.0,
    reviewCount: 542,
    specs: {
      memory: "24GB GDDR6X",
      coreClock: "2520 MHz Boost",
      interface: "PCIe 4.0",
      features: ["Ray Tracing", "DLSS 3", "AV1 Encode", "8K Ready"],
    },
    vendor: "NVIDIA Elite Partners",
    featured: true,
  },
]

// Demo Users
window.DEMO_USERS = {
  buyer: {
    email: "buyer@demo.com",
    password: "buyer123",
    role: "buyer",
    name: "Demo Buyer",
  },
  seller: {
    email: "seller@demo.com",
    password: "seller123",
    role: "seller",
    name: "Demo Seller",
  },
  admin: {
    email: "admin@demo.com",
    password: "admin123",
    role: "admin",
    name: "Demo Admin",
  },
}

// Configuration
window.CONFIG = {
  siteName: "NeoMarket",
  currency: "USD",
  taxRate: 0.1,
  shippingRate: 15.0,
  freeShippingThreshold: 500,
}
