// Mock Database - Products Configuration

const products = [
  {
    id: "prod-001",
    title: "NVIDIA GeForce RTX 4090 24GB",
    brand: "NVIDIA",
    category: "gpu",
    description:
      "Ultimate gaming graphics card with 24GB GDDR6X memory. Experience unparalleled performance in 4K gaming and content creation.",
    modelNumber: "RTX4090-24G",
    price: 1599.99,
    originalPrice: 1799.99,
    condition: "new",
    stock: 15,
    images: [
      "/pic/nvidia-rtx-4090-graphics-card.jpg",
      "/pic/nvidia-rtx-4090-front-view.jpg",
      "/pic/nvidia-rtx-4090-side-view.jpg",
    ],
    primaryImage: "/pic/nvidia-rtx-4090-graphics-card.jpg",
    specs: {
      vram: "24GB GDDR6X",
      coreClock: "2.52 GHz",
      interface: "PCIe 4.0",
      power: "450W",
    },
    rating: 4.8,
    reviewCount: 234,
    vendorId: "vendor-001",
    vendorName: "TechGear Pro",
    verified: true,
    warranty: 36,
    shippingFrom: "US",
    badges: ["new", "fast-shipping"],
  },
  {
    id: "prod-002",
    title: "AMD Radeon RX 7900 XTX 24GB",
    brand: "AMD",
    category: "gpu",
    description: "High-performance AMD GPU with excellent 4K gaming capabilities and ray tracing support.",
    modelNumber: "RX7900XTX-24G",
    price: 999.99,
    originalPrice: null,
    condition: "new",
    stock: 23,
    images: [
      "/pic/amd-rx-7900-xtx-graphics-card.jpg",
      "/pic/amd-rx-7900-xtx-front.jpg",
      "/pic/amd-rx-7900-xtx-cooler.jpg",
    ],
    primaryImage: "/pic/amd-rx-7900-xtx-graphics-card.jpg",
    specs: {
      vram: "24GB GDDR6",
      coreClock: "2.5 GHz",
      interface: "PCIe 4.0",
      power: "355W",
    },
    rating: 4.6,
    reviewCount: 189,
    vendorId: "vendor-002",
    vendorName: "GamersHub",
    verified: true,
    warranty: 24,
    shippingFrom: "US",
    badges: ["new"],
  },
  {
    id: "prod-003",
    title: "Logitech G Pro X Superlight",
    brand: "Logitech",
    category: "mice",
    description:
      "Ultra-lightweight wireless gaming mouse designed for esports professionals. Weighs less than 63 grams.",
    modelNumber: "GPRO-SUPERLIGHT",
    price: 149.99,
    originalPrice: null,
    condition: "new",
    stock: 42,
    images: ["/pic/logitech-g-pro-x-superlight-gaming-mouse.jpg", "/pic/logitech-g-pro-x-mouse-top-view.jpg"],
    primaryImage: "/pic/logitech-g-pro-x-superlight-gaming-mouse.jpg",
    specs: {
      dpi: "25,600 DPI",
      weight: "63g",
      connectivity: "Wireless",
      battery: "70 hours",
    },
    rating: 4.9,
    reviewCount: 512,
    vendorId: "vendor-001",
    vendorName: "TechGear Pro",
    verified: true,
    warranty: 12,
    shippingFrom: "US",
    badges: ["new"],
  },
  {
    id: "prod-004",
    title: "Razer DeathAdder V3 Pro",
    brand: "Razer",
    category: "mice",
    description: "Ergonomic wireless gaming mouse with Focus Pro 30K sensor and up to 90 hours of battery life.",
    modelNumber: "RZ01-04630",
    price: 129.99,
    originalPrice: 149.99,
    condition: "new",
    stock: 31,
    images: ["/pic/razer-deathadder-v3-pro-gaming-mouse.jpg", "/pic/razer-deathadder-v3-side-view.jpg"],
    primaryImage: "/pic/razer-deathadder-v3-pro-gaming-mouse.jpg",
    specs: {
      dpi: "30,000 DPI",
      weight: "63g",
      connectivity: "Wireless",
      battery: "90 hours",
    },
    rating: 4.7,
    reviewCount: 387,
    vendorId: "vendor-003",
    vendorName: "PeripheralsPro",
    verified: true,
    warranty: 12,
    shippingFrom: "US",
    badges: [],
  },
  {
    id: "prod-005",
    title: "Corsair K70 RGB TKL",
    brand: "Corsair",
    category: "keyboards",
    description: "Tenkeyless mechanical gaming keyboard with Cherry MX switches and per-key RGB lighting.",
    modelNumber: "CH-9119014",
    price: 169.99,
    originalPrice: null,
    condition: "new",
    stock: 28,
    images: ["/pic/corsair-k70-rgb-tkl-mechanical-keyboard.jpg", "/pic/corsair-k70-keyboard-front.jpg"],
    primaryImage: "/pic/corsair-k70-rgb-tkl-mechanical-keyboard.jpg",
    specs: {
      switches: "Cherry MX Red",
      connectivity: "Wired",
      layout: "TKL",
      lighting: "Per-key RGB",
    },
    rating: 4.6,
    reviewCount: 276,
    vendorId: "vendor-001",
    vendorName: "TechGear Pro",
    verified: true,
    warranty: 24,
    shippingFrom: "US",
    badges: ["new"],
  },
  {
    id: "prod-006",
    title: "Keychron Q1 Pro QMK",
    brand: "Keychron",
    category: "keyboards",
    description: "Premium wireless mechanical keyboard with QMK/VIA support and hot-swappable switches.",
    modelNumber: "Q1-PRO",
    price: 199.99,
    originalPrice: null,
    condition: "new",
    stock: 19,
    images: ["/pic/keychron-q1-pro-mechanical-keyboard.jpg"],
    primaryImage: "/pic/keychron-q1-pro-mechanical-keyboard.jpg",
    specs: {
      switches: "Gateron Pro",
      connectivity: "Wireless/Wired",
      layout: "75%",
      lighting: "RGB",
    },
    rating: 4.8,
    reviewCount: 198,
    vendorId: "vendor-002",
    vendorName: "GamersHub",
    verified: true,
    warranty: 12,
    shippingFrom: "US",
    badges: ["new"],
  },
  {
    id: "prod-007",
    title: "ASUS ROG Swift PG27AQDM",
    brand: "ASUS",
    category: "monitors",
    description: "27-inch OLED gaming monitor with 1440p resolution, 240Hz refresh rate, and 0.03ms response time.",
    modelNumber: "PG27AQDM",
    price: 899.99,
    originalPrice: 999.99,
    condition: "new",
    stock: 12,
    images: ["/pic/asus-rog-swift-oled-gaming-monitor.jpg"],
    primaryImage: "/pic/asus-rog-swift-oled-gaming-monitor.jpg",
    specs: {
      size: "27 inch",
      resolution: "2560x1440",
      refreshRate: "240Hz",
      panel: "OLED",
    },
    rating: 4.9,
    reviewCount: 142,
    vendorId: "vendor-001",
    vendorName: "TechGear Pro",
    verified: true,
    warranty: 36,
    shippingFrom: "US",
    badges: ["new"],
  },
  {
    id: "prod-008",
    title: "Samsung Odyssey G9",
    brand: "Samsung",
    category: "monitors",
    description: "49-inch ultra-wide curved gaming monitor with 1440p resolution and 240Hz refresh rate.",
    modelNumber: "LC49G95T",
    price: 1299.99,
    originalPrice: 1499.99,
    condition: "new",
    stock: 8,
    images: ["/pic/samsung-odyssey-g9-ultrawide-monitor.jpg", "/pic/samsung-odyssey-g9-front-view.jpg"],
    primaryImage: "/pic/samsung-odyssey-g9-ultrawide-monitor.jpg",
    specs: {
      size: "49 inch",
      resolution: "5120x1440",
      refreshRate: "240Hz",
      panel: "VA",
    },
    rating: 4.7,
    reviewCount: 231,
    vendorId: "vendor-003",
    vendorName: "PeripheralsPro",
    verified: true,
    warranty: 24,
    shippingFrom: "US",
    badges: [],
  },
  {
    id: "prod-009",
    title: "Intel Core i9-14900K",
    brand: "Intel",
    category: "cpu",
    description: "High-performance 24-core processor with 32 threads, perfect for gaming and content creation.",
    modelNumber: "i9-14900K",
    price: 589.99,
    originalPrice: null,
    condition: "new",
    stock: 25,
    images: ["/pic/intel-core-i9-14900k-processor.jpg"],
    primaryImage: "/pic/intel-core-i9-14900k-processor.jpg",
    specs: {
      cores: "24 cores",
      threads: "32 threads",
      baseClock: "3.2 GHz",
      boostClock: "6.0 GHz",
    },
    rating: 4.8,
    reviewCount: 167,
    vendorId: "vendor-002",
    vendorName: "GamersHub",
    verified: true,
    warranty: 36,
    shippingFrom: "US",
    badges: ["new"],
  },
  {
    id: "prod-010",
    title: "AMD Ryzen 9 7950X",
    brand: "AMD",
    category: "cpu",
    description: "16-core, 32-thread processor with impressive multi-threaded performance and gaming capabilities.",
    modelNumber: "7950X",
    price: 549.99,
    originalPrice: 699.99,
    condition: "new",
    stock: 18,
    images: ["/pic/ryzen-9-7950x.jpg"],
    primaryImage: "/pic/ryzen-9-7950x.jpg",
    specs: {
      cores: "16 cores",
      threads: "32 threads",
      baseClock: "4.5 GHz",
      boostClock: "5.7 GHz",
    },
    rating: 4.9,
    reviewCount: 203,
    vendorId: "vendor-001",
    vendorName: "TechGear Pro",
    verified: true,
    warranty: 36,
    shippingFrom: "US",
    badges: [],
  },
]

// Categories
const categories = [
  { id: "cat-001", name: "Graphics Cards", slug: "gpu", parentId: null },
  { id: "cat-002", name: "Gaming Mice", slug: "mice", parentId: null },
  { id: "cat-003", name: "Keyboards", slug: "keyboards", parentId: null },
  { id: "cat-004", name: "Monitors", slug: "monitors", parentId: null },
  { id: "cat-005", name: "Processors", slug: "cpu", parentId: null },
]

// Brands
const brands = ["NVIDIA", "AMD", "Intel", "Logitech", "Razer", "Corsair", "ASUS", "Samsung", "Keychron"]

// Constants
const STORAGE_KEYS = {
  CART: "neomarket_cart",
  WISHLIST: "neomarket_wishlist",
  USER_SESSION: "neomarket_session",
  PRODUCTS: "neomarket_products",
}

if (!localStorage.getItem(STORAGE_KEYS.PRODUCTS)) {
  localStorage.setItem(STORAGE_KEYS.PRODUCTS, JSON.stringify(products))
}

window.APP_CONFIG = {
  products,
  categories,
  brands,
  STORAGE_KEYS,
}
